### ISSUE TITLE
Trying in the Chinese dataset?

### ISSUE THREAD

**Issue by eclipse-du** [LinyangLee/KNN-BERT#1]
Does anyone trying to use Chinese dataset and getting the result.Thx!

**Comment by LinyangLee** [comment]
Haven't tried. 
I assume that it should be working.

**Comment by ahtamjan** [comment]
Where can I get the codes ?  Many Thx !

**Comment by LinyangLee** [comment]
very soon,  hopefully no later than a month !

**Comment by ahtamjan** [comment]
> very soon, hopefully no later than a month !

Thank you!
