### ISSUE TITLE
Moco queue update

### ISSUE THREAD

**Issue by wwx13** [LinyangLee/KNN-BERT#2]
I have head through paper, and I wonder  how moco realized in this paper.

My question are:

1. how many moco?
   Is there only one moco queue exist, and when a query  input, use  query label select the same or not the same sample in moco?
   or you keep n moco queues, n is the same as classify num ?

2. how moco queue update samples?   
   I think it can only update by temp input batch data. All query of temp batch also input into key encoder,  then they will  put into moco queue .
   I do not have any other idea of this question.

hOpe ur relay~

**Comment by LinyangLee** [comment]
we will release the code before the end of this month!

**Comment by wwx13** [comment]
> we will release the code before the end of this month!

Thanks...
