### ISSUE TITLE
请教关于resume training from checkpoint

### ISSUE THREAD

**Issue by huangyiqian-h1kk** [LinyangLee/KNN-BERT#4]
作者们好！我最近在参考KNN-BERT这个项目进行自己的研究，使用了自己的数据集跑了KNN-BERT的模型。
当我试图参考hugging face documentation使用命令行，通过resume_from_checkpoint实现resume training from checkpoint时，发现trainer和trainingargs并不支持。我试图通过详细查看training_args.py，my_trainer.py和run_main.py三个文件来了解resume training from checkpoint的实现方式，可能是我huggingface经验较少，还是不太理解。
可以向您各位请教一下这个问题吗？谢谢

**Comment by LinyangLee** [comment]
sry for the late repsonse. plz check the hf transformers docs.
